### ISSUE TITLE
thanks for you code and test errors!

### ISSUE THREAD

**Issue by zilesazoyi2** [DeNA/Chainer_Realtime_Multi-Person_Pose_Estimation#18]
could you give me some advice ? thank you !　ありがとうございます

sun@sunwin:~/0newcodedownother/Chainer_Realtime_Multi-Person_Pose_Estimation-master$ python pose_detector.py posenet models/coco_posenet.npz --img data/person.png --gpu 0
Traceback (most recent call last):
  File "pose_detector.py", line 12, in <module>
    from entity import params, JointType
  File "/home/sun/0newcodedownother/Chainer_Realtime_Multi-Person_Pose_Estimation-master/entity.py", line 4, in <module>
    from models.CocoPoseNet import CocoPoseNet
ImportError: No module named models.CocoPoseNet

**Comment by zilesazoyi2** [comment]
thanks you so much !!   I   reinstall  Chainer and all things go well ！Ｏ（∩＿∩）Ｏ

ありがとうございます

**Comment by leetenki** [comment]
ω・。) Oh... that's nice.

**Comment by leetenki** [comment]
This problem was solved.

**Comment by burnzzz** [comment]
I think I have the same issue:
```
> python pose_detector.py posenet models/coco_posenet.npz --img data/person.png
Traceback (most recent call last):
  File "pose_detector.py", line 11, in <module>
    from entity import params, JointType
  File "/home/xxx/tools/pose/Chainer_Realtime_Multi-Person_Pose_Estimation/entity.py", line 3, in <module>
    from models.CocoPoseNet import CocoPoseNet
ImportError: No module named models.CocoPoseNet
```

Here is the output of
```
> ls -l models

-rw-rw-r-- 1 xxx xxx 194385881 Feb 14 00:13 coco_posenet.npz
-rw-rw-r-- 1 xxx xxx         15897 Feb 14 00:06 CocoPoseNet.py
-rw-rw-r-- 1 xxx xxx         11044 Feb 14 00:11 CocoPoseNet.pyc
-rw-rw-r-- 1 xxx xxx           6853 Feb 14 00:06 convert_model.py
-rw-rw-r-- 1 xxx xxx           8559 Feb 14 00:06 FaceNet.py
-rw-rw-r-- 1 xxx xxx           6291 Feb 14 00:12 FaceNet.pyc
-rw-rw-r-- 1 xxx xxx       676709 Feb 14 00:06 haarcascade_frontalface_alt.xml
-rw-rw-r-- 1 xxx xxx 136663176 Feb 14 00:14 handnet.npz
-rw-rw-r-- 1 xxx xxx           8559 Feb 14 00:06 HandNet.py
-rw-rw-r-- 1 xxx xxx           6291 Feb 14 00:12 HandNet.pyc
-rw-rw-r-- 1 xxx xxx 147344024 Nov 13  2016 pose_iter_102000.caffemodel
-rw-rw-r-- 1 xxx xxx 153717332 Apr 26  2017 pose_iter_116000.caffemodel
-rw-rw-r-- 1 xxx xxx 209274056 Dez  9  2016 pose_iter_440000.caffemodel
```

I also tried to reinstall chainer:
```
sudo -H pip3 install --upgrade chainer
```
but it did not change anything.
